# This is a basic workflow to help you get started with Actions

name: actualizar

on:
  schedule:
  - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  actualizar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Get data
        run: |
          cd getData
          pip install -r requirements.txt  
          pwd
          python getData.py
          
      - name: Commit data files
        run: |
          pwd
          
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          git gc
          git add -A
          git commit -a -m "Added new date" || echo "Nothing to commit"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true  
          
      - name: Deploy
        run: |
          git remote set-url origin https://${github_token}@github.com/${repository}
          npm run deploy
        env:
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
